version: '3'
services:
  minio:
    container_name: sample4-minio
    hostname: sample4-minio
    ports:
      - "9000:9000" # api
      - "9001:9001" # console
    user: root
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z

    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    entrypoint: >
      /bin/sh -c "
      mkdir -p /export/test-bucket;
      minio server /export --address :9000 --console-address :9001;
      "
    volumes:
      - ./minio/data:/export

