version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
    environment:
      - PORT=8080